export const PROXY_SERVER = "https://web-production-38ff.up.railway.app";
export const FEED_SOURCES = {
  ARXIV_ML: {
    FEED: "https://export.arxiv.org/api/query?search_query=cat:cs.LG&sortBy=submittedDate&sortOrder=descending",
    WEB_LINK: "https://arxiv.org/list/cs.LG/recent",
    TYPE: "scipapers",
    NAME: "Arxiv Machine Learning Papers",
    ENABLED: false,
    ARTICLE_NUM: 10,
  },
  ARXIV_AI: {
    FEED: "https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending",
    WEB_LINK: "https://arxiv.org/list/cs.AI/recent",
    TYPE: "scipapers",
    NAME: "Arxiv AI Papers",
    ENABLED: true,
    ARTICLE_NUM: 10,
  },
  TWO_MINUTE_PAPERS: {
    FEED: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    WEB_LINK: "https://www.youtube.com/c/K%C3%A1rolyZsolnai/featured",
    TYPE: "videos",
    NAME: "Two Minute Papers",
    ENABLED: false,
    ARTICLE_NUM: 5,
  },
  MICROSOFT: {
    FEED: "https://www.microsoft.com/en-us/research/feed/",
    WEB_LINK:
      "https://www.microsoft.com/en-us/research/blog/category/intelligence/artifical-intelligence/",
    TYPE: "articles",
    NAME: "Microsoft AI",
    ENABLED: true,
    ARTICLE_NUM: 5,
  },
  NVIDIA: {
    FEED: "https://feeds.feedburner.com/nvidiablog?format=xml",
    WEB_LINK: "https://news.developer.nvidia.com/blog/",
    TYPE: "articles",
    NAME: "Nvidia AI",
    ENABLED: true,
    ARTICLE_NUM: 5,
  },
  DEEPMIND: {
    FEED: "https://deepmind.com/blog/feed/basic/",
    WEB_LINK: "https://deepmind.com/blog",
    TYPE: "articles",
    NAME: "Deep Mind",
    ENABLED: true,
    ARTICLE_NUM: 5,
  },
  OPENAI: {
    FEED: "https://openai.com/blog/rss/",
    WEB_LINK: "https://openai.com/blog/",
    TYPE: "articles",
    NAME: "OpenAI",
    ENABLED: true,
    ARTICLE_NUM: 5,
  },
  AMAZON: {
    FEED: "https://aws.amazon.com/blogs/machine-learning/feed/",
    WEB_LINK: "https://aws.amazon.com/blogs/machine-learning/",
    TYPE: "articles",
    NAME: "Amazon AI",
    ENABLED: true,
    ARTICLE_NUM: 5,
  },
  YANNIC_KILCHER: {
    FEED: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew",
    WEB_LINK: "https://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew",
    TYPE: "videos",
    NAME: "Yannic Kilcher",
    ENABLED: false,
    ARTICLE_NUM: 5,
  },
  WHATS_AI: {
    FEED: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUzGQrN-lyyc0BWTYoJM_Sg",
    WEB_LINK: "https://www.youtube.com/channel/UCUzGQrN-lyyc0BWTYoJM_Sg",
    TYPE: "videos",
    NAME: "What's AI",
    ENABLED: false,
    ARTICLE_NUM: 5,
  },
  LEX_FRIDMAN: {
    FEED: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
    WEB_LINK: "https://www.youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA",
    TYPE: "videos",
    NAME: "Lex Fridman",
    ENABLED: false,
    ARTICLE_NUM: 5,
  },
  GOOGLE: {
    FEED: "http://feeds.feedburner.com/blogspot/gJZg?format=xml",
    WEB_LINK: "https://ai.googleblog.com/",
    TYPE: "scipapers",
    NAME: "Google AI",
    ENABLED: true,
    ARTICLE_NUM: 5,
  },
};
